version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
  desafio:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_PASS: postgres
      DATABASE_USER: postgres
      AUTH_SECRET: S0m3_S3cR3t
      NODE_ENV: production
    ports:
      - 3000:3000
    links:
      - db
  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - db
