version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: challenge_pass
      POSTGRES_DB: challenge
      POSTGRES_USER: challenge_user
    ports:
      - 3306:3306
    expose:
      - 3306
  desafio:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: challenge
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_PASS: challenge_pass
      DATABASE_USER: challenge_user
      NODE_ENV: production
    ports:
      - 3000:3000
    links:
      - db
  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - db
